### ISSUE TITLE
Add images? 

### ISSUE THREAD

**Issue by gbinal** [GSA/participation-playbook#3]
I'm not sure that's necessary but I can show you how to add if helpful.

**Comment by jalbertbowden** [comment]
status of this?
or rather, is this the repo for https://participation.usa.gov/?

**Comment by gbinal** [comment]
Thanks for the reminder.  This issue can be closed.

**Comment by jalbertbowden** [comment]
that wasn't a reminder, sorry it seemed like that.
came here to add some alt text to images in the playbook, they still are without.
as a rule for reproducibility, as well as remixing, all assets need to be included.

**Comment by JustinHerman** [comment]
We're about to undergo a complete redesign of the playbook, and these will be addressed. Thank you for pointing out and contributing!
